version: '3.7'

services:
  mc-redis:
    image: redis:latest
    restart: always
    container_name: mc-redis
    expose:
      - 6379
    networks:
      - mc-network
    environment: 
      TZ: Asia/Shanghai
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf 
      - ./data/redis-data:/data      
    command: redis-server /etc/redis/redis.conf

  mc-gocq:
    image: silicer/go-cqhttp
    restart: always
    container_name: mc-gocq
    expose:
      - 9091
    networks:
      - mc-network
    depends_on: 
      - mc-nonebot
    volumes:
      - ./configs/go-cqhttp.yml:/data/config.yml
      - ./data/go-cqhttp/logs:/data/logs
      - ./data/go-cqhttp/data:/data/data
  
  mc-nonebot:
    build: ./nonebot
    restart: always
    container_name: mc-nonebot
    expose:  
      - 9092
    networks:
      - mc-network
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nonebot:/root/nonebot
    command: python3 /root/nonebot/bot.py
  
  mc-core:
    build: ./channel
    restart: always
    container_name: mc-core
    ports:
      - 9090:8000
    expose:
      - 8000
    networks:
      - mc-network
    depends_on: 
      - mc-redis
      - mc-gocq
    command: uvicorn server:message_channel --host 0.0.0.0 --port 8000
  
networks:
  mc-network:
    driver: bridge