version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: mc-redis
    expose:
      - 6379
    environment: 
      TZ: Asia/Shanghai
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf 
      - ./data/redis-data:/data      
    command: redis-server /etc/redis/redis.conf

  go-cqhttp:
    image: silicer/go-cqhttp
    restart: always
    container_name: mc-gocq
    ports:
      - 9091:5700
    links:
      - nonebot:mc-nonebot
    depends_on: 
      - nonebot
    volumes:
      - ./configs/go-cqhttp.yml:/data/config.yml
      - ./data/go-cqhttp/logs:/data/logs
      - ./data/go-cqhttp/data:/data/data
  
  nonebot:
    build: ./nonebot
    restart: always
    container_name: mc-nonebot
    expose:  
      - 9092
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./nonebot:/root/nonebot"
    command: python3 /root/nonebot/bot.py
  
  message-channel:
    build: ./channel
    restart: always
    container_name: mc-core
    ports:
      - 8080:8080
    links:
      - redis:mc-redis
    command: uvicorn server:message_channel --host 0.0.0.0 --port 8080