version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: mc-redis
    ports:
      - 9090:6379
    environment: 
      TZ: Asia/Shanghai
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf 
      - ./data/redis-data:/data      
    command: redis-server /etc/redis/redis.conf

  go-cqhttp:
    image: silicer/go-cqhttp
    restart: always
    container_name: mc-gocq
    ports:
      - 9091:5700
    volumes:
      - ./configs/go-cqhttp.yml:/data/config.yml
      - ./data/go-cqhttp/logs:/data/logs
      - ./data/go-cqhttp/data:/data/data